import { describe, expect, it } from 'vitest'
import datasetJson from '../../docs/recognition-optimization/RCO-5-007-B6_CHALLENGE_DATASET.json'
import priorB0Json from '../../docs/recognition-optimization/RCO-5-005-B0_DEVELOPMENT_DATASET.json'
import priorB02Json from '../../docs/recognition-optimization/RCO-5-005-B02_DEVELOPMENT_DATASET.json'
import priorB1Json from '../../docs/recognition-optimization/RCO-5-006-B1_DEVELOPMENT_DATASET.json'
import priorB2Json from '../../docs/recognition-optimization/RCO-5-007-B2_CHALLENGE_DATASET.json'
import priorB3Json from '../../docs/recognition-optimization/RCO-5-007-B3_CHALLENGE_DATASET.json'
import priorB4Json from '../../docs/recognition-optimization/RCO-5-007-B4_CHALLENGE_DATASET.json'
import priorB5Json from '../../docs/recognition-optimization/RCO-5-007-B5_CHALLENGE_DATASET.json'
import { validateScopeReferenceCandidate, type ImmutableScopeIndex, type ScopeReferenceCandidate, type ScopeReferenceDirective, type ScopeReferenceObservation, type SurfaceReference } from './scopeReferenceContract'
import { indexImmutableScopesV11 } from './scopeIndexV11'
import { TASK_FORMATION_P3_POLICY_VERSION } from './taskFormationPolicyP3'
import { REVISION_RELATION_RESOLVER_VERSION, type RevisionRelationKind } from './revisionRelationResolver'

type ExpectedSurface = { scopeText: string; surface: string }
type ExpectedDirective = Omit<ScopeReferenceDirective, 'id' | 'propositionScopeIds' | 'action' | 'object' | 'timeRefs' | 'materialRefs' | 'eventRef' | 'locationRef' | 'revisionRefs'> & { expectedId: string; propositionScopeTexts: string[]; action: ExpectedSurface; object: ExpectedSurface; timeRefs: Array<ExpectedSurface & { type: ScopeReferenceDirective['timeRefs'][number]['type'] }>; materialRefs: Array<ExpectedSurface & { required: boolean }>; eventRef: ExpectedSurface | null; locationRef: ExpectedSurface | null; revisionRefs: ScopeReferenceDirective['revisionRefs']; expectedDefaultSelected: boolean }
type ExpectedObservation = Omit<ScopeReferenceObservation, 'id' | 'propositionScopeIds' | 'subject' | 'timeRefs' | 'locationRef'> & { expectedId: string; propositionScopeTexts: string[]; subject: ExpectedSurface; timeRefs: Array<ExpectedSurface & { type: ScopeReferenceObservation['timeRefs'][number]['type'] }>; locationRef: ExpectedSurface | null }
interface ExpectedRelation { kind: RevisionRelationKind; targetExpectedId: string; replacementExpectedIds: string[]; evidenceScopeTexts: string[]; resolution: 'shared_scope' | 'same_scope_position' | 'adjacent_unique_referent'; referentType: string | null }
interface DatasetCase { id: string; semanticFamilyId: string; coverageTags: string[]; sourceTitle: string; sourceText: string; referenceTime: string; timezone: string; expected: { requiresAction: boolean; directives: ExpectedDirective[]; observations: ExpectedObservation[]; ignoredScopeTexts: string[]; forbiddenDefaultSurfaces: string[]; revisionRelations: ExpectedRelation[]; unresolvedRevisionScopeTexts: string[] } }
interface Dataset { schemaVersion: string; datasetId: string; split: string; classification: string; seenStatus: string; labelProvenance: string; taskFormationPolicyVersion: string; revisionResolverVersion: string; sampleCount: number; cases: DatasetCase[] }
const dataset = datasetJson as Dataset
const priors = [priorB0Json, priorB02Json, priorB1Json, priorB2Json, priorB3Json, priorB4Json, priorB5Json] as Array<{ cases: Array<{ sourceText: string; semanticFamilyId?: string }> }>
function grams(value: string): Set<string> { const normalized = value.normalize('NFKC').replace(/[\s\p{P}\p{S}]/gu, '').toLowerCase(); return new Set(Array.from({ length: Math.max(0, normalized.length - 1) }, (_, index) => normalized.slice(index, index + 2))) }
function jaccard(left: string, right: string): number { const a = grams(left); const b = grams(right); const intersection = [...a].filter((item) => b.has(item)).length; const union = new Set([...a, ...b]).size; return union === 0 ? 1 : intersection / union }
function lookup(index: ImmutableScopeIndex, text: string): string { const matches = index.scopes.filter((scope) => scope.text === text); expect(matches, text).toHaveLength(1); return matches[0].id }
function surface(index: ImmutableScopeIndex, value: ExpectedSurface): SurfaceReference { return { scopeId: lookup(index, value.scopeText), surface: value.surface } }
function materialize(fixture: DatasetCase, index: ImmutableScopeIndex): ScopeReferenceCandidate { return { schemaVersion: 'scope-reference-candidate-1.0', sourceId: index.sourceId, sourceVersionId: index.sourceVersionId, sourceFingerprint: index.sourceFingerprint, producerRunId: `reference-${fixture.id}`, requiresAction: fixture.expected.requiresAction, directives: fixture.expected.directives.map((item) => ({ id: item.expectedId, propositionScopeIds: item.propositionScopeTexts.map((text) => lookup(index, text)), semantics: item.semantics, inferenceLevel: item.inferenceLevel, actionType: item.actionType, action: surface(index, item.action), object: surface(index, item.object), effect: item.effect, timeRefs: item.timeRefs.map((ref) => ({ ...surface(index, ref), type: ref.type })), materialRefs: item.materialRefs.map((ref) => ({ ...surface(index, ref), required: ref.required })), eventRef: item.eventRef ? surface(index, item.eventRef) : null, locationRef: item.locationRef ? surface(index, item.locationRef) : null, revisionRefs: [] })), observations: fixture.expected.observations.map((item) => ({ id: item.expectedId, kind: item.kind, propositionScopeIds: item.propositionScopeTexts.map((text) => lookup(index, text)), semantics: item.semantics, inferenceLevel: item.inferenceLevel, subject: surface(index, item.subject), timeRefs: item.timeRefs.map((ref) => ({ ...surface(index, ref), type: ref.type })), locationRef: item.locationRef ? surface(index, item.locationRef) : null })), ignoredScopeIds: fixture.expected.ignoredScopeTexts.map((text) => lookup(index, text)) } }

describe('RCO-5-007-B6 pre-oracle challenge dataset', () => {
  it('has a fixed anonymous identity created only after P3 freeze', () => { expect(dataset).toMatchObject({ schemaVersion: 'rco-5-007-b6-challenge-1.0.0', datasetId: 'rco-5-007-b6-challenge-20260904', split: 'Development-Challenge', sampleCount: 16 }); expect(dataset.seenStatus).toBe('UNSEEN_BY_P3_AT_FREEZE_AND_UNSEEN_BY_DEEPSEEK'); expect(dataset.taskFormationPolicyVersion).toBe(TASK_FORMATION_P3_POLICY_VERSION); expect(dataset.revisionResolverVersion).toBe(REVISION_RELATION_RESOLVER_VERSION) })
  it('does not reuse source text or semantic families from B0 through B5', () => { const oldCases = priors.flatMap((prior) => prior.cases); const oldTexts = new Set(oldCases.map((item) => item.sourceText)); const oldFamilies = new Set(oldCases.map((item) => item.semanticFamilyId).filter(Boolean)); expect(new Set(dataset.cases.map((item) => item.id)).size).toBe(16); expect(new Set(dataset.cases.map((item) => item.semanticFamilyId)).size).toBe(16); for (const fixture of dataset.cases) { expect(oldTexts.has(fixture.sourceText)).toBe(false); expect(oldFamilies.has(fixture.semanticFamilyId)).toBe(false); expect(Math.max(...oldCases.map((item) => jaccard(fixture.sourceText, item.sourceText)))).toBeLessThan(0.55) } })
  it('contains no obvious identifier, credential or secret', () => { const text = dataset.cases.map((item) => `${item.sourceTitle}\n${item.sourceText}`).join('\n'); expect(text).not.toMatch(/\b1[3-9]\d{9}\b|\b\d{15,18}[0-9Xx]\b|[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|(?:api|access)[-_ ]?key\s*[:=]/iu) })
  it('materializes every Expected task into the frozen scope-reference contract', async () => { for (const fixture of dataset.cases) { const index = await indexImmutableScopesV11(fixture.id, 'source-v1', fixture.sourceText); expect(validateScopeReferenceCandidate(materialize(fixture, index), index), fixture.id).toEqual({ valid: true, issues: [] }) } })
  it('binds every expected relation and unresolved state to local immutable scopes', async () => { for (const fixture of dataset.cases) { const index = await indexImmutableScopesV11(fixture.id, 'source-v1', fixture.sourceText); const ids = new Set(fixture.expected.directives.map((item) => item.expectedId)); for (const relation of fixture.expected.revisionRelations) { expect(ids.has(relation.targetExpectedId), fixture.id).toBe(true); expect(relation.replacementExpectedIds.every((id) => ids.has(id)), fixture.id).toBe(true); relation.evidenceScopeTexts.forEach((text) => lookup(index, text)) } fixture.expected.unresolvedRevisionScopeTexts.forEach((text) => lookup(index, text)) } })
  it('covers each revision edge twice plus ambiguity and non-task cancellation', () => { const relations = dataset.cases.flatMap((item) => item.expected.revisionRelations); for (const kind of ['cancels', 'supersedes', 'amends'] as const) expect(relations.filter((item) => item.kind === kind)).toHaveLength(2); expect(dataset.cases.filter((item) => item.coverageTags.includes('revision')).length).toBeGreaterThanOrEqual(8); expect(dataset.cases.flatMap((item) => item.expected.unresolvedRevisionScopeTexts)).toHaveLength(2) })
  it('keeps defaults conservative and Expected out of request projection', async () => { const allowed = new Set(['review', 'fill', 'prepare', 'carry', 'save', 'print', 'complete']); for (const fixture of dataset.cases) { for (const item of fixture.expected.directives) { if (!item.expectedDefaultSelected) continue; expect(item.semantics).toMatchObject({ actor: 'addressee', speechAct: 'directive', polarity: 'affirmative', tense: 'future', status: 'pending', validity: 'active', modality: 'required' }); expect(allowed.has(item.actionType)).toBe(true); expect(['local_change', 'physical_action']).toContain(item.effect) } const index = await indexImmutableScopesV11(fixture.id, 'source-v1', fixture.sourceText); const projection = { sourceId: fixture.id, sourceVersionId: 'source-v1', sourceFingerprint: index.sourceFingerprint, sourceTitle: fixture.sourceTitle, sourceText: fixture.sourceText, referenceTime: fixture.referenceTime, timezone: fixture.timezone, scopeCatalog: index.scopes.map(({ id, order, text }) => ({ id, order, text })) }; expect(JSON.stringify(projection)).not.toMatch(/expected|revisionRelations|unresolvedRevision|forbiddenDefault|expectedDefaultSelected|semanticFamilyId/iu) } })
})
